<?php if($this->getOrder() && $this->getOrder()->getPayment()->getMethod() == "BoletoBancario_standard"): ?>
    <br/>
    <?php switch (strtolower($this->getTagType())) : ?>
        <?php case 'link': ?>
            <a href="<?php echo $this->getUrl('BoletoBancario/standard/view/order_id/' . $this->getOrder()->getId()) ?>" class="link-cart" target="_blank"><?php echo $this->__('Clique aqui para imprimir o Boleto') ?><img src="<?php echo($this->getSkinUrl('images/boleto/boleto.gif')) ?>" /></a>
            <?php break; ?>
        <?php default: ?>
            <button type="button" class="button" onclick="window.open('<?php echo $this->getUrl('BoletoBancario/standard/view/order_id/' . $this->getOrder()->getId()) ?>')"><span><span><?php echo $this->__('Clique aqui para imprimir o Boleto') ?></span></span><img src="<?php echo($this->getSkinUrl('images/boleto/boleto.gif')) ?>" /></button>
    <?php endswitch; ?>
    <br/>
<?php endif; ?>