<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>A segunda via foi enviada.</title>
	<style>
		body
		{
			font-family: sans-serif;
		}
		h1
		{
			font-size: 22px;
		}
		p, a
		{
			font-size: 14px;
		}
	</style>
</head>
<body>
	<h1>Segunda via do Boleto</h1>
	<p>A segunda via do boleto foi enviada para o cliente por e-mail.</p>

	<a href="javascript:window.close()">Fechar</a>
</body>
</html>